### ISSUE TITLE
Play next song in list

### ISSUE THREAD

**Issue by Fxbouffant** [dekztah/sc2#16]
The next song in the list doesn't seem to auto-play. It is intended or am I missing something ?

Btw, great job ! I've been looking for something like this for a long time :)

**Comment by dekztah** [comment]
Yeah, I have thought about this before, but this should be optional, like a setting. I will see into it.
And thanks for the feedback :)

**Comment by dekztah** [comment]
This should be working now, filters are also affecting which is the next track (if you hide reposts, those will not be queued). I have added this is a setting which is off by default (fast forward icon)

**Comment by dekztah** [comment]
... and its not working properly... advancing to next track inside a playlist has incorrect logic
