### ISSUE TITLE
tabbed loading

### ISSUE THREAD

**Issue by dekztah** [dekztah/sc2#18]
should not load all data on init. followings and favorites should be loaded on tab press....

**Comment by dekztah** [comment]
09bef673852649c910922e3771d303c90ef4763a

**Comment by pledgeofficial** [comment]
bro me and my friends have been waiting for ages for the page to work again, when will it work.

**Comment by dekztah** [comment]
i'm on it, but its a complete refactoring of code. i'm doing this in my free time, i think next week is highly probable :)

**Comment by dekztah** [comment]
it's deployed (with many new bugs). can you please check if you are able to use it?
