### ISSUE TITLE
Hide playlists

### ISSUE THREAD

**Issue by ChrisMCMine** [dekztah/sc2#6]
More and more soundcloud users start to create playlists with single tracks from other users instead of reposting tracks so that the tracks still show up with tools like sc2.

So a setting to hide single-track playlists would be useful.

As you can see there are three playlists with just a single track from another user in the screenshot.
![image](https://cloud.githubusercontent.com/assets/1984051/11876520/7c407e9e-a4ea-11e5-8855-1c91e67a3d92.png)

**Comment by dekztah** [comment]
Hmmm. Why do they do that? Anyways, I can make a filter for that, its not much work.

**Comment by dekztah** [comment]
stopped working
